module.exports = {
	printWidth: 80,
	useTabs: true,
	tabWidth: 1,
	singleQuote: true,
	bracketSpacing: true,
	trailingComma: 'all',
	semi: true,
	importOrder: [
		'^react',
		'',
		'^@core/(.*)$',
		'^@server/(.*)$',
		'',
		'^@ui/(.*)$',
		'',
		'<THIRD_PARTY_MODULES>',
		'',
		'^@modules/common/hooks(.*)$',
		'',
		'^@utils/(.*)$',
		'',
		'^@public/(.*)$',
		'',
		'^@(.*)/(.*)/types(.*)$',
		'',
		'',
		'^@assets/(.*)$',
		'^@modules/(.*)/assets/(.*)$',
		'',
		'^[./]',
		'',
	],
	importOrderBuiltinModulesToTop: true,
	importOrderCaseInsensitive: true,
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	importOrderMergeDuplicateImports: true,
	importOrderCombineTypeAndValueImports: true,
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
};
